// <auto-generated />
using System;
using FieldFix.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FieldFix.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("FieldFix.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServiceRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "Tech A-14",
                            Category = "Infrastructure",
                            CreatedAt = new DateTime(2026, 9, 17, 23, 32, 37, 965, DateTimeKind.Utc).AddTicks(3600),
                            Description = "Passenger panel is not responding and requires a field inspection.",
                            Location = "Grand Central",
                            Priority = "High",
                            RequestedBy = "Transit Operations",
                            Status = "Assigned",
                            Title = "Broken elevator panel"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Tech B-09",
                            Category = "Equipment",
                            CreatedAt = new DateTime(2026, 9, 18, 0, 32, 37, 965, DateTimeKind.Utc).AddTicks(3610),
                            Description = "Sensor alarm is intermittently triggering on the inbound escalator.",
                            Location = "42nd Street",
                            Priority = "Medium",
                            RequestedBy = "Station Operations",
                            Status = "In Progress",
                            Title = "Escalator sensor fault"
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Unassigned",
                            Category = "Safety",
                            CreatedAt = new DateTime(2026, 9, 18, 1, 32, 37, 965, DateTimeKind.Utc).AddTicks(3620),
                            Description = "Multiple platform lights are out after a power fluctuation.",
                            Location = "Atlantic Avenue",
                            Priority = "Low",
                            RequestedBy = "Customer Service",
                            Status = "Open",
                            Title = "Lighting outage"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
